/* Generated by Yosys 0.66+183 (git sha1 b285b72e3, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 13.2.1) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "rtl/dsm.v:12.1-152.10" *)
module dsm(clk, rst_n, sample_valid, audio_sample, threshold, alert_flag, clear_alert, crossing_count, window_done);
  (* src = "rtl/dsm.v:16.42-16.45" *)
  input clk;
  wire clk;
  (* src = "rtl/dsm.v:17.42-17.47" *)
  input rst_n;
  wire rst_n;
  (* src = "rtl/dsm.v:20.42-20.54" *)
  input sample_valid;
  wire sample_valid;
  (* src = "rtl/dsm.v:21.43-21.55" *)
  input signed [15:0] audio_sample;
  wire signed [15:0] audio_sample;
  (* src = "rtl/dsm.v:24.42-24.51" *)
  input [8:0] threshold;
  wire [8:0] threshold;
  (* src = "rtl/dsm.v:27.42-27.52" *)
  output alert_flag;
  reg alert_flag;
  (* src = "rtl/dsm.v:28.42-28.53" *)
  input clear_alert;
  wire clear_alert;
  (* src = "rtl/dsm.v:29.42-29.56" *)
  output [8:0] crossing_count;
  reg [8:0] crossing_count;
  (* src = "rtl/dsm.v:30.42-30.53" *)
  output window_done;
  reg window_done;
  (* src = "rtl/dsm.v:83.5-128.8" *)
  wire [8:0] _000_;
  (* src = "rtl/dsm.v:83.5-128.8" *)
  wire [8:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  (* src = "rtl/dsm.v:49.35-49.44" *)
  reg [8:0] cross_ctr;
  (* src = "rtl/dsm.v:46.35-46.46" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14" *)
  wire signed [15:0] prev_sample;
  (* src = "rtl/dsm.v:47.35-47.45" *)
  reg prev_valid;
  (* src = "rtl/dsm.v:48.35-48.45" *)
  reg [8:0] sample_ctr;
  (* src = "rtl/dsm.v:53.10-53.19" *)
  wire sign_curr;
  (* src = "rtl/dsm.v:54.10-54.19" *)
  wire sign_prev;
  (* onehot = 32'd1 *)
  reg [3:0] state;
  assign _091_ = ~state[1];
  assign _092_ = sample_ctr[1] & sample_ctr[0];
  assign _093_ = sample_ctr[2] & _092_;
  assign _094_ = sample_ctr[3] & _093_;
  assign _095_ = sample_ctr[4] & _094_;
  assign _096_ = sample_ctr[5] & _095_;
  assign _097_ = sample_ctr[6] & _096_;
  assign _098_ = ~(sample_ctr[7] & _097_);
  assign _099_ = sample_ctr[7] | _097_;
  assign _100_ = state[2] & _099_;
  assign _001_[7] = _098_ & _100_;
  assign _101_ = sample_ctr[6] | _096_;
  assign _102_ = state[2] & _101_;
  assign _001_[6] = _102_ & ~(_097_);
  assign _103_ = sample_ctr[5] | _095_;
  assign _104_ = state[2] & _103_;
  assign _001_[5] = _104_ & ~(_096_);
  assign _105_ = sample_ctr[4] | _094_;
  assign _106_ = state[2] & _105_;
  assign _001_[4] = _106_ & ~(_095_);
  assign _107_ = sample_ctr[3] | _093_;
  assign _108_ = state[2] & _107_;
  assign _001_[3] = _108_ & ~(_094_);
  assign _109_ = sample_ctr[2] | _092_;
  assign _110_ = state[2] & _109_;
  assign _001_[2] = _110_ & ~(_093_);
  assign _111_ = sample_ctr[1] | sample_ctr[0];
  assign _112_ = state[2] & _111_;
  assign _001_[1] = _112_ & ~(_092_);
  assign _001_[0] = state[2] & ~(sample_ctr[0]);
  assign _113_ = cross_ctr[1] & cross_ctr[0];
  assign _114_ = cross_ctr[2] & _113_;
  assign _115_ = cross_ctr[3] & _114_;
  assign _116_ = cross_ctr[4] & _115_;
  assign _117_ = cross_ctr[5] & _116_;
  assign _118_ = cross_ctr[6] & _117_;
  assign _011_ = ~(cross_ctr[7] & _118_);
  assign _012_ = cross_ctr[7] | _118_;
  assign _013_ = state[2] & _012_;
  assign _000_[7] = _011_ & _013_;
  assign _014_ = cross_ctr[6] | _117_;
  assign _015_ = state[2] & _014_;
  assign _000_[6] = _015_ & ~(_118_);
  assign _016_ = cross_ctr[5] | _116_;
  assign _017_ = state[2] & _016_;
  assign _000_[5] = _017_ & ~(_117_);
  assign _018_ = cross_ctr[4] | _115_;
  assign _019_ = state[2] & _018_;
  assign _000_[4] = _019_ & ~(_116_);
  assign _020_ = cross_ctr[3] | _114_;
  assign _021_ = state[2] & _020_;
  assign _000_[3] = _021_ & ~(_115_);
  assign _022_ = cross_ctr[2] | _113_;
  assign _023_ = state[2] & _022_;
  assign _000_[2] = _023_ & ~(_114_);
  assign _024_ = cross_ctr[1] | cross_ctr[0];
  assign _025_ = state[2] & _024_;
  assign _000_[1] = _025_ & ~(_113_);
  assign _000_[0] = state[2] & ~(cross_ctr[0]);
  assign _026_ = state[2] | state[0];
  assign _027_ = state[3] | _026_;
  assign _028_ = state[1] | _027_;
  assign _029_ = sample_valid | ~(state[2]);
  assign _009_ = _028_ & _029_;
  assign _030_ = threshold[8] | ~(cross_ctr[8]);
  assign _031_ = threshold[7] | ~(cross_ctr[7]);
  assign _032_ = threshold[6] | ~(cross_ctr[6]);
  assign _033_ = ~(_031_ & _032_);
  assign _034_ = cross_ctr[7] | ~(threshold[7]);
  assign _035_ = cross_ctr[6] | ~(threshold[6]);
  assign _036_ = _034_ & _035_;
  assign _037_ = cross_ctr[5] | ~(threshold[5]);
  assign _038_ = ~(_036_ & _037_);
  assign _039_ = ~(_033_ | _038_);
  assign _040_ = threshold[4] | ~(cross_ctr[4]);
  assign _041_ = threshold[5] | ~(cross_ctr[5]);
  assign _042_ = _040_ & _041_;
  assign _043_ = cross_ctr[4] | ~(threshold[4]);
  assign _044_ = _042_ & _043_;
  assign _045_ = _039_ & _044_;
  assign _046_ = threshold[3] | ~(cross_ctr[3]);
  assign _047_ = cross_ctr[3] | ~(threshold[3]);
  assign _048_ = ~(cross_ctr[3] ^ threshold[3]);
  assign _049_ = cross_ctr[2] & ~(threshold[2]);
  assign _050_ = ~(cross_ctr[2] ^ threshold[2]);
  assign _051_ = _048_ & _050_;
  assign _052_ = cross_ctr[0] | ~(threshold[0]);
  assign _053_ = cross_ctr[1] & ~(threshold[1]);
  assign _054_ = ~(cross_ctr[1] ^ threshold[1]);
  assign _055_ = _052_ & _054_;
  assign _056_ = ~(_051_ & _055_);
  assign _057_ = ~(_051_ & _053_);
  assign _058_ = ~(_047_ & _049_);
  assign _059_ = _046_ & _058_;
  assign _060_ = _057_ & _059_;
  assign _061_ = ~(_056_ & _060_);
  assign _062_ = ~(_045_ & _061_);
  assign _063_ = _042_ | ~(_039_);
  assign _064_ = ~(_033_ & _034_);
  assign _065_ = _063_ & _064_;
  assign _066_ = ~(_062_ & _065_);
  assign _067_ = threshold[0] | ~(cross_ctr[0]);
  assign _068_ = _067_ & ~(_056_);
  assign _069_ = ~(_045_ & _068_);
  assign _070_ = cross_ctr[8] | ~(threshold[8]);
  assign _071_ = _069_ & _070_;
  assign _072_ = ~(_066_ & _071_);
  assign _073_ = ~(_030_ & _072_);
  assign _074_ = _091_ | _073_;
  assign _075_ = sample_ctr[8] | _098_;
  assign _076_ = ~(state[2] & _075_);
  assign _077_ = clear_alert & state[3];
  assign _078_ = state[0] & sample_valid;
  assign _079_ = ~(_077_ | _078_);
  assign _080_ = _076_ & _079_;
  assign _004_ = ~(_074_ & _080_);
  assign _003_ = state[2] & ~(_075_);
  assign _002_ = state[0] & ~(sample_valid);
  assign _081_ = ~(sample_ctr[8] ^ _098_);
  assign _001_[8] = state[2] & _081_;
  assign _008_ = state[2] & sample_valid;
  assign _082_ = ~(cross_ctr[8] ^ _011_);
  assign _000_[8] = state[2] & _082_;
  assign _006_ = _027_ & _029_;
  assign _083_ = ~(audio_sample[15] & prev_sample[15]);
  assign _084_ = audio_sample[15] | prev_sample[15];
  assign _085_ = sample_valid & prev_valid;
  assign _086_ = _084_ & _085_;
  assign _087_ = ~(_083_ & _086_);
  assign _088_ = ~(state[2] & _087_);
  assign _010_ = _028_ & _088_;
  assign _089_ = ~(state[1] & _073_);
  assign _007_ = state[1] ? _073_ : _077_;
  assign _090_ = clear_alert | ~(state[3]);
  assign _005_ = ~(_089_ & _090_);
  (* src = "rtl/dsm.v:83.5-128.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cross_ctr[0] <= 1'h0;
    else if (_010_) cross_ctr[0] <= _000_[0];
  (* src = "rtl/dsm.v:83.5-128.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cross_ctr[1] <= 1'h0;
    else if (_010_) cross_ctr[1] <= _000_[1];
  (* src = "rtl/dsm.v:83.5-128.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cross_ctr[2] <= 1'h0;
    else if (_010_) cross_ctr[2] <= _000_[2];
  (* src = "rtl/dsm.v:83.5-128.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cross_ctr[3] <= 1'h0;
    else if (_010_) cross_ctr[3] <= _000_[3];
  (* src = "rtl/dsm.v:83.5-128.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cross_ctr[4] <= 1'h0;
    else if (_010_) cross_ctr[4] <= _000_[4];
  (* src = "rtl/dsm.v:83.5-128.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cross_ctr[5] <= 1'h0;
    else if (_010_) cross_ctr[5] <= _000_[5];
  (* src = "rtl/dsm.v:83.5-128.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cross_ctr[6] <= 1'h0;
    else if (_010_) cross_ctr[6] <= _000_[6];
  (* src = "rtl/dsm.v:83.5-128.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cross_ctr[7] <= 1'h0;
    else if (_010_) cross_ctr[7] <= _000_[7];
  (* src = "rtl/dsm.v:83.5-128.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cross_ctr[8] <= 1'h0;
    else if (_010_) cross_ctr[8] <= _000_[8];
  (* src = "rtl/dsm.v:83.5-128.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) sample_ctr[0] <= 1'h0;
    else if (_009_) sample_ctr[0] <= _001_[0];
  (* src = "rtl/dsm.v:83.5-128.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) sample_ctr[1] <= 1'h0;
    else if (_009_) sample_ctr[1] <= _001_[1];
  (* src = "rtl/dsm.v:83.5-128.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) sample_ctr[2] <= 1'h0;
    else if (_009_) sample_ctr[2] <= _001_[2];
  (* src = "rtl/dsm.v:83.5-128.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) sample_ctr[3] <= 1'h0;
    else if (_009_) sample_ctr[3] <= _001_[3];
  (* src = "rtl/dsm.v:83.5-128.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) sample_ctr[4] <= 1'h0;
    else if (_009_) sample_ctr[4] <= _001_[4];
  (* src = "rtl/dsm.v:83.5-128.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) sample_ctr[5] <= 1'h0;
    else if (_009_) sample_ctr[5] <= _001_[5];
  (* src = "rtl/dsm.v:83.5-128.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) sample_ctr[6] <= 1'h0;
    else if (_009_) sample_ctr[6] <= _001_[6];
  (* src = "rtl/dsm.v:83.5-128.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) sample_ctr[7] <= 1'h0;
    else if (_009_) sample_ctr[7] <= _001_[7];
  (* src = "rtl/dsm.v:83.5-128.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) sample_ctr[8] <= 1'h0;
    else if (_009_) sample_ctr[8] <= _001_[8];
  reg \prev_sample_reg[15] ;
  (* src = "rtl/dsm.v:83.5-128.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \prev_sample_reg[15]  <= 1'h0;
    else if (_008_) \prev_sample_reg[15]  <= audio_sample[15];
  assign prev_sample[15] = \prev_sample_reg[15] ;
  (* src = "rtl/dsm.v:133.5-150.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) crossing_count[0] <= 1'h0;
    else if (state[1]) crossing_count[0] <= cross_ctr[0];
  (* src = "rtl/dsm.v:133.5-150.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) crossing_count[1] <= 1'h0;
    else if (state[1]) crossing_count[1] <= cross_ctr[1];
  (* src = "rtl/dsm.v:133.5-150.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) crossing_count[2] <= 1'h0;
    else if (state[1]) crossing_count[2] <= cross_ctr[2];
  (* src = "rtl/dsm.v:133.5-150.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) crossing_count[3] <= 1'h0;
    else if (state[1]) crossing_count[3] <= cross_ctr[3];
  (* src = "rtl/dsm.v:133.5-150.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) crossing_count[4] <= 1'h0;
    else if (state[1]) crossing_count[4] <= cross_ctr[4];
  (* src = "rtl/dsm.v:133.5-150.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) crossing_count[5] <= 1'h0;
    else if (state[1]) crossing_count[5] <= cross_ctr[5];
  (* src = "rtl/dsm.v:133.5-150.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) crossing_count[6] <= 1'h0;
    else if (state[1]) crossing_count[6] <= cross_ctr[6];
  (* src = "rtl/dsm.v:133.5-150.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) crossing_count[7] <= 1'h0;
    else if (state[1]) crossing_count[7] <= cross_ctr[7];
  (* src = "rtl/dsm.v:133.5-150.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) crossing_count[8] <= 1'h0;
    else if (state[1]) crossing_count[8] <= cross_ctr[8];
  (* src = "rtl/dsm.v:133.5-150.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) alert_flag <= 1'h0;
    else if (_007_) alert_flag <= state[1];
  (* src = "rtl/dsm.v:83.5-128.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prev_valid <= 1'h0;
    else if (_006_) prev_valid <= state[2];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state[0] <= 1'h1;
    else state[0] <= _002_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state[1] <= 1'h0;
    else state[1] <= _003_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state[2] <= 1'h0;
    else state[2] <= _004_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state[3] <= 1'h0;
    else state[3] <= _005_;
  (* src = "rtl/dsm.v:133.5-150.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) window_done <= 1'h0;
    else window_done <= state[1];
  assign sign_prev = prev_sample[15];
  assign sign_curr = audio_sample[15];
endmodule
